;; -*- lexical-binding: t;-*-
(setq inhibt-startup-message t)
(menu-bar-mode -1)
(global-display-line-numbers-mode t)
(setq scroll-conservatively 101)
(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)
(setq-default c-basic-offset 4)
(electric-pair-mode 1)
(set-charset-priority 'unicode)
(prefer-coding-system 'utf-8)
(setq locale-coding-system 'utf-8)
(setq use-short-answers t)
(setq make-backup-files nil)
(setq auto-save-default nil)
(setq create-lockfiles nil)

(defun my-save-or-kill-buffer ()
  (interactive)
  (if (and (buffer-file-name) (buffer-modified-p))
      (if (y-or-n-p "Save buffer? ")
          (save-buffer)
        (kill-buffer (current-buffer)))
    (kill-buffer (current-buffer))))
(global-set-key (kbd "C-c C-k") #'my-save-or-kill-buffer)

(global-set-key (kbd "M-h") 'backward-char)
(global-set-key (kbd "M-j") 'next-line)
(global-set-key (kbd "M-k") 'previous-line)
(global-set-key (kbd "M-l") 'forward-char)
(global-set-key (kbd "M-u") 'backward-word)
(global-set-key (kbd "M-i") 'forward-word)
(global-set-key (kbd "M-n") 'scroll-down-command)
(global-set-key (kbd "M-m") 'scroll-up-command)
(global-set-key (kbd "M-o") 'beginning-of-line)
(global-set-key (kbd "M-p") 'end-of-line)
(global-set-key (kbd "M-'") 'backward-delete-char-untabify)

(global-set-key (kbd "M-q") 'copy-region-as-kill)
